# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'primary.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(322, 506)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_in_stoc = QtWidgets.QLabel(self.centralwidget)
        self.label_in_stoc.setGeometry(QtCore.QRect(100, 20, 111, 121))
        self.label_in_stoc.setText("")
        self.label_in_stoc.setPixmap(QtGui.QPixmap("img/in_stock.png"))
        self.label_in_stoc.setScaledContents(True)
        self.label_in_stoc.setObjectName("label_in_stoc")
        self.pushButtonInStoc = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonInStoc.setGeometry(QtCore.QRect(60, 140, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(6)
        self.pushButtonInStoc.setFont(font)
        self.pushButtonInStoc.setObjectName("pushButtonInStoc")
        self.label_from_stoc = QtWidgets.QLabel(self.centralwidget)
        self.label_from_stoc.setGeometry(QtCore.QRect(104, 260, 111, 115))
        self.label_from_stoc.setText("")
        self.label_from_stoc.setPixmap(QtGui.QPixmap("img/pngwing.com (1).png"))
        self.label_from_stoc.setScaledContents(True)
        self.label_from_stoc.setObjectName("label_from_stoc")
        self.pushButtonCheckout = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCheckout.setGeometry(QtCore.QRect(80, 380, 162, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.pushButtonCheckout.setFont(font)
        self.pushButtonCheckout.setObjectName("pushButtonCheckout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 322, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actiondark_amber = QtWidgets.QAction(MainWindow)
        self.actiondark_amber.setObjectName("actiondark_amber")
        self.actiondark_blue = QtWidgets.QAction(MainWindow)
        self.actiondark_blue.setObjectName("actiondark_blue")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonInStoc.setText(_translate("MainWindow", "Поступление на склад"))
        self.pushButtonCheckout.setText(_translate("MainWindow", "Офорить заказ"))
        self.actiondark_amber.setText(_translate("MainWindow", "dark amber"))
        self.actiondark_blue.setText(_translate("MainWindow", "dark blue"))
